### ISSUE TITLE
Dropwizard 0.8.3 and 0.8.4 support

### ISSUE THREAD

**Issue by scho** [HubSpot/dropwizard-guice#67] opened 2015-08-26 07:41 UTC
There are two new dropwizard releases, [0.8.3](https://github.com/dropwizard/dropwizard/releases/tag/v0.8.3) and [0.8.4](https://github.com/dropwizard/dropwizard/releases/tag/v0.8.4).

I am not sure whether it makes sense to support these two, since 0.9.0 is just around the corner. Just wanted to mention it.

I tried to fix it by updating jersey and the hk2 stuff, but I got failing tests.

**Comment by oddcb** [comment] 2015-08-26 12:41
Hi. I'm in the progress of migrating an app from DW 0.7 to 0.8.x. With dropwizard-juice 0.8.2.0 and dropwizard 0.8.3 tests are running, but fails on 0.8.4. I see jersey has been upgraded from 2.19 til 2.21 in 0.8.4 and I guess that might be the problem? 

Getting exceptions saying:  ```java.lang.IllegalStateException: ServiceLocatorImpl(GuiceServiceLocator-1,0,7646139) has been shut down``` 

Dropwizard on the master branch also seems to rely on 2.21.

**Comment by scho** [comment] 2015-08-26 13:07
We currently use dropwizard `0.8.2` with dropwizard-guice `0.8.2.0` and it runs smoothly.

I got the same exception as you when running the tests.

**Comment by kaiwaldron** [comment] 2015-09-02 03:34
Running into the same issue when trying to use drop wizard 0.8.4.

**Comment by oddcb** [comment] 2015-09-02 07:30
Seems also to be reported here: https://github.com/Squarespace/jersey2-guice/issues/32

**Comment by walterhuangfs** [comment] 2015-09-09 21:51
I'm using Dropwizard 0.8.2 and dropwizard-guice 0.8.2.0. Running into the same issue.

Able to address it by adding "BootstrapUtils.reset()" to the tests to reset Guice 

Notice in the documentation https://github.com/HubSpot/dropwizard-guice, under Testing part.

> As of Dropwizard 0.8.x, when writing Integration Tests using DropwizardAppRule, you need to reset jersey2-guice by running:

> BootstrapUtils.reset(); "

I have a test using DropwizardAppRule, so I need to reset in other tests too. Hope this helps.

**Comment by scho** [comment] 2015-09-10 08:22
I don't think that this is the issue. Upgrading jersey to `2.21` and hk2-api to `2.4.0-b31` in dropwizard-guice gives me the following exception when running `HK2LinkerTest` even though it runs `BootstrapUtils.reset()` (at the moment it runs with `@AfterClass`, but `@After` does not help either):
```
java.lang.IllegalStateException: ServiceLocatorImpl(GuiceServiceLocator-1,0,433287555) has been shut down
	at org.jvnet.hk2.internal.ServiceLocatorImpl.checkState(ServiceLocatorImpl.java:2270)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.create(ServiceLocatorImpl.java:961)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.createAndInitialize(ServiceLocatorImpl.java:1055)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.createAndInitialize(ServiceLocatorImpl.java:1047)
	at com.hubspot.dropwizard.guice.HK2LinkerTest.jitGuiceBindingsAreBridgedToHk2(HK2LinkerTest.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

I get the same exception when running `InjectedIntegrationTest`.

**Comment by yunspace** [comment] 2015-09-13 12:54
I'm currently using `DW 0.9.0-rc3` with `dropwizard-guice 0.8.2.0` (jersey 2.19) at work. Everything seems fine, except sometimes when I debug and take too long I get the `ServiceLocatorImpl has been shutdown` exception.

I tried using `DW 0.8.4` with the existing hk2 `2.4.0-b25` and all unit/integration tests are passing. If I upgrade hk2 to `2.4.0-b31` then I start to get various Class and Method not found errors. I'm using Java `1.8.0_45`

@scho try using just `DW 0.8.4` with the current `hk2 2.4.0-b25` and see how that turns out?

**Comment by scho** [comment] 2015-09-13 15:31
@yunspace I don't think that it is an option to combine `DW 0.8.4` with `dropwizard-guice 0.8.2.0`. Because you end up with two different versions of `jersey` and `hk2` on your classpath. If `dropwizard-guice`' version gets picked, everything is fine. If `dropwizard`s version is active, you run into errors.

In my opinion we should figure out how to make `dropwizard-guice` working with `jersey 2.21` and `hk2 2.4.0-b31`.

**Comment by scho** [comment] 2015-09-13 16:38
Merging #68 would at least add support for `dropwizard 0.8.3`. Can't we merge it?

**Comment by yunspace** [comment] 2015-09-13 22:30
@scho I see, being at the mercy of the maven dependency resolver is not a good place to be.

In regards to #68, only @eliast or @jhaber have merge access.

**Comment by ryansmithevans** [comment] 2015-09-22 15:50
Got mine working with this combo:-
            'com.hubspot.dropwizard:dropwizard-guice:0.8.3.0'
            'org.glassfish.hk2:hk2:2.4.0-b25'
            'io.dropwizard:dropwizard-core:0.9.0-rc3'

**Comment by scho** [comment] 2015-09-23 09:04
It looks like dropwizard changed the jersey version recently quite frequently (`dropwizard` => `jersey`):
`0.8.3` => `2.19`
`0.8.4` => `2.21`
`0.9.0-rc1` => `2.18`
`0.9.0-rc2` => `2.19`
`0.9.0-rc3` => `2.19`
`0.9.0-rc4` => `2.21`

Anyway, `dropwizard-guice` should support `jersey:2.21` at some point.

**Comment by jhaber** [comment] 2015-09-23 22:16
I bumped the necessary versions in d5cf3ee85654ff1ba31921493f9b3a0192edade6 I'll see if I can get the tests passing

**Comment by scho** [comment] 2015-09-27 12:29
According to Squarespace/jersey2-guice#32, this change is the cause of the problem:
https://github.com/jersey/jersey/commit/ad54f0033c73144f1ad23706583714a3fe84bee7#diff-5b1ed0a8d396a2ef75d665e0e0459524

**Comment by jhaber** [comment] 2015-09-28 01:51
I pushed a branch [here](https://github.com/HubSpot/dropwizard-guice/tree/servicelocatorfix) that prevents the `ServiceLocator` from being shut down prematurely and makes the tests pass, but I'm not sure if this could cause resource leaks? I can look into it more deeply some time this week but for now feel free to build and test out that branch

**Comment by hotmeatballsoup** [comment] 2015-11-12 17:35
Hi all - so I'm a bit confused - can I use this lib in my DW 0.8.5 project or not?

**Comment by alexan** [comment] 2015-11-12 17:37
there is no released version which is compatible with 0.8.5 or 0.9.x

**Comment by hotmeatballsoup** [comment] 2015-11-12 18:06
Thanks @alexan any (ballpark) estimated time frame? Not being impatient, just curious!

**Comment by jhaber** [comment] 2015-11-12 18:12
I pushed a branch with a [fix](https://github.com/HubSpot/dropwizard-guice/commit/3355c9a08b31560176409f8e7501a48e79229755) for the issues being reported with 0.8.4, but so far no one has confirmed that it works in their application so I haven't cut a new release yet (the tests pass though). 

I haven't looked at 0.8.5, but it's possible that the same [branch](https://github.com/HubSpot/dropwizard-guice/tree/servicelocatorfix) will work with 0.8.5 as well

**Comment by hotmeatballsoup** [comment] 2015-11-12 18:15
Gotchya @jhaber - in the next few days I'm going to be creating a mock DW 0.8.5 and plan on using this lib/plugin if at all possible. I'll keep you posted on how I fair - thanks for the prompt responses here!

**Comment by oddcb** [comment] 2015-11-18 11:13
Hi @jhaber - I've set up our application with a build of your branch and DW 0.8.4 + 0.8.5. Builds ok and just some preliminary clicking around suggests it works. Haven't tested it more thoroughly, so no idea about any leaks. Any particular tips on what to look for?

**Comment by jhaber** [comment] 2015-11-18 14:23
From what I recall, it wouldn't start up at all with 0.8.4 previously so that's a good sign. I'll cut a 0.8.4 release so more people can test it out

**Comment by jhaber** [comment] 2015-11-18 14:37
I just released 0.8.4.0, if no one reports any issues in the next few days I'll close this issue

**Comment by ESPNMichaelKidd** [comment] 2015-11-18 14:44
@jhaber any idea how long it typically takes for the release to get to maven central?

**Comment by jhaber** [comment] 2015-11-18 15:20
It shouldn't take very long, try adding the dependency and running `mvn -U dependency:resolve`

**Comment by ESPNMichaelKidd** [comment] 2015-11-18 20:17
seems to be working with dw 0.8.4 and 0.8.5 so far

**Closed** 2016-06-02 17:05 UTC
